import { Card, CardContent } from "../components/ui/card";
import { AlertTriangle } from "lucide-react";

export default function DisclaimerPage() {
  return (
    <div className="max-w-5xl mx-auto px-6 py-10">
      <div className="mb-10">
        <h1 className="text-4xl font-bold text-[#005BEA]">
          Disclaimer
        </h1>

        <p className="text-gray-600 mt-3">
          Last Updated: June 2026
        </p>
      </div>

      <Card>
        <CardContent className="p-8 space-y-8">
          <div className="flex items-start gap-4 rounded-xl border border-amber-200 bg-amber-50 p-5">
            <AlertTriangle className="h-8 w-8 text-amber-600 flex-shrink-0" />

            <div>
              <h2 className="font-semibold text-amber-800 mb-2">
                Important Notice
              </h2>

              <p className="text-amber-700">
                MediPredict is an educational and research project. Predictions
                generated by this platform should not be considered official
                insurance quotations or professional financial advice.
              </p>
            </div>
          </div>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              1. Educational Purpose
            </h2>

            <p className="text-gray-600">
              MediPredict was developed as a final-year academic project to
              demonstrate machine learning, explainable AI, full-stack
              development, and predictive analytics concepts. The platform is
              intended solely for educational and demonstration purposes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              2. No Insurance Advice
            </h2>

            <p className="text-gray-600">
              The premium estimates generated by MediPredict do not constitute
              insurance, financial, legal, or medical advice. Users should
              consult licensed insurance providers or qualified professionals
              before making decisions based on premium estimates.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              3. Prediction Limitations
            </h2>

            <p className="text-gray-600">
              Premium predictions are generated using machine learning models
              trained on available datasets. Actual insurance premiums may vary
              significantly depending on underwriting policies, insurer-specific
              risk assessments, market conditions, and additional information
              not considered by the model.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              4. Explainability Information
            </h2>

            <p className="text-gray-600">
              The feature contribution and explainability information displayed
              within the platform are intended to improve transparency and help
              users understand how the machine learning model arrived at its
              prediction. These explanations should not be interpreted as
              absolute measures of real-world insurance risk.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              5. Limitation of Liability
            </h2>

            <p className="text-gray-600">
              The MediPredict team shall not be held responsible for any loss,
              damages, claims, or decisions resulting from the use of this
              platform or reliance upon any prediction, analysis, or
              recommendation generated by the system.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              6. Contact Information
            </h2>

            <p className="text-gray-600">
              Email: teammedipredict@gmail.com
              <br />
              Phone: +91 98363 08844
              <br />
              Location: Kolkata, India
            </p>
          </section>
        </CardContent>
      </Card>
    </div>
  );
}