import { Card, CardContent } from "../components/ui/card";

export default function TermsOfServicePage() {
  return (
    <div className="max-w-5xl mx-auto px-6 py-10">
      <div className="mb-10">
        <h1 className="text-4xl font-bold text-[#005BEA]">
          Terms of Service
        </h1>

        <p className="text-gray-600 mt-3">
          Last Updated: June 2026
        </p>
      </div>

      <Card>
        <CardContent className="p-8 space-y-8">
          <section>
            <h2 className="text-xl font-semibold mb-3">
              1. Acceptance of Terms
            </h2>

            <p className="text-gray-600">
              By accessing and using MediPredict, you agree to comply with and
              be bound by these Terms of Service. If you do not agree with any
              part of these terms, you should discontinue use of the platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              2. Purpose of the Platform
            </h2>

            <p className="text-gray-600">
              MediPredict is an AI-powered insurance premium prediction system
              developed for educational, research, and demonstration purposes.
              The platform provides estimated premium values using machine
              learning techniques and explainable AI methodologies.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              3. User Responsibilities
            </h2>

            <p className="text-gray-600">
              Users are responsible for providing accurate information when
              generating predictions. Inaccurate or misleading inputs may result
              in inaccurate premium estimates.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              4. Prediction Accuracy
            </h2>

            <p className="text-gray-600">
              While MediPredict aims to generate realistic estimates, no
              guarantee is made regarding the accuracy, completeness, or
              reliability of predictions. Actual insurance premiums may differ
              significantly from generated estimates.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              5. Limitation of Liability
            </h2>

            <p className="text-gray-600">
              MediPredict and its developers shall not be held liable for any
              financial, medical, insurance, or business decisions made based on
              information generated by the platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              6. Intellectual Property
            </h2>

            <p className="text-gray-600">
              All source code, designs, documentation, visual assets, and
              machine learning implementations associated with MediPredict
              remain the intellectual property of the project team unless
              otherwise stated.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              7. Modifications
            </h2>

            <p className="text-gray-600">
              The project team reserves the right to modify, suspend, or
              discontinue any part of the platform without prior notice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              8. Contact Information
            </h2>

            <p className="text-gray-600">
              Email: teammedipredict@gmail.com
              <br />
              Phone: +91 98363 08844
              <br />
              Location: Kolkata, India
            </p>
          </section>
        </CardContent>
      </Card>
    </div>
  );
}